import Head from 'next/head'
import Header from '../components/Header.js'
import Banner from '@/components/Banner.js'
import SmallCards from '@/components/SmallCards.js';
import Medium from '@/components/Medium.js';
import LargeCards from '@/components/LargeCards.js';
import Footer from '@/components/Footer.js';

export const getStaticProps = async () => {
   const res = await fetch('https://www.jsonkeeper.com/b/4G1G');
   const setData = await res.json();
   const card = await fetch('https://www.jsonkeeper.com/b/VHHT');
   const cardsData = await card.json();
   return{
     props:{
       data:setData,
       cards:cardsData
     }
   }
}
const Home = ({data,cards}) => {

  return (
    <div>
      <Head>
        <title>Airbnb 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <Banner/>

      <main className='max-w-7xl mx-auto px-8 sm:px-16 scroll-smooth bg-slate-100 drop-shadow'>
        <section className='my-7 pt-10'>
          <h2 className='text-3xl font-bold'>
            Explore Nearby
          </h2>

          <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 my-7'>
          {data.map(({img,distance,location}) => (
            <SmallCards 
            key={img}
            img={img}
            location={location}
            distance={distance}
            />
          ))}
          </div>
          
           

        </section>   

        <section>
            <h1 className='text-3xl font-bold my-5'>Chose what you want</h1>

            <div className='flex overflow-scroll scrollbar-hide gap-3 text-center p-3 -ml-3'>
              {cards.map(({img,title}) => (
              <Medium 
              key={img}
              img={img}
              title={title}
              />
            ))}
              
            </div>
            
        </section> 

        <LargeCards
        img={'https://links.papareact.com/4cj'}
        title='The Greatest Experience'
        description={'Wishlist curated by AIRBNB'}
        buttonText='Get Inspiration'
        />
      </main>

      <Footer/>
      
    </div>
  )
}

export default Home
